import Head from "next/head";
import styles from "@/styles/Home.module.css";
import LaptopCard from "@/components/dashboard/_laptopCard";
import ScrollToTop from "@/components/scrollToTop";
// import { useRef } from 'react';
interface Laptop {
  image: string;
  brand: string;
  model: string;
  strikePrice: number;
  price: number;
  ram: string;
  gpu: string;
  processor: string;
  disk: string;
  os: string;
  display: string;
  name: string;
}

export default function Home({ data }: { data: any }) {
  // const scrollRef = useRef(null);
  // useScrollSnap({ ref: scrollRef, duration: 100, delay: 50 });
  const laptops: Laptop[] = data;
  return (
    <>
      <Head>
        <title>Laptops</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <section className={styles.bigContainer}>
        <section className={styles.wrapper}>
          <div className={styles.top}>ZIIIP</div>
          <div
            className={styles.bottom}
            aria-hidden="true">
            ZIIIP
          </div>
        </section>
        <section className={styles.snapChild}>
          {/* <Dashboard /> */}

          {laptops.map((laptop, index) => (
            <LaptopCard
              laptop={laptop}
              key={index}></LaptopCard>
          ))}

          <ScrollToTop
            styles={{
              width: "100vw",
              textAlign: "center",
              backgroundColor: "#000",
              height: "5rem",
              color: "#fff",
              gridColumn: "1/-1",
              marginLeft: "-2rem",
              marginBottom: "-1rem",
            }}
          />
        </section>
      </section>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const res = await fetch("http://localhost:3000/api/laptops");
  const data = await res.json();
  // console.log(data)
  // const data = "weeeeeeeeee"
  return {
    props: {
      data,
    }, // will be passed to the page component as props
  };
}
